services:
  postgres:
    image: postgres:16-alpine
    container_name: nasa-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nasa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
