services:
  postgres:
    image: postgres:15-alpine
    container_name: nasa-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nasa_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
